@FreakyFashion_HostAddress = https://localhost:8000

### Get all products
GET {{FreakyFashion_HostAddress}}/api/Products/
Accept: application/json

### Get product by Id
GET {{FreakyFashion_HostAddress}}/api/Products/1
Accept: application/json

### Get product by slug
GET {{FreakyFashion_HostAddress}}/api/Products/slug=t-shirt
Accept: application/json

### Create a new product
POST {{FreakyFashion_HostAddress}}/api/Products/
Accept: application/json
Content-Type: application/json
{
    "name": "Yellow Cap",
    "Description": "Very nice cap",
    "Price": 49,
    "Image": "/images/yellow-cap.png",
    "CategoryId": 8
}

### Create without body
POST {{FreakyFashion_HostAddress}}/api/Products/
Accept: application/json
Content-Type: application/json
{

}

### Delete product
DELETE {{FreakyFashion_HostAddress}}/api/Products/3
Accept: application/json

### -------------------------------------------------------------
### Get All Categories
GET {{FreakyFashion_HostAddress}}/api/Categories/
Accept: application/json

### Get Category By Id
GET {{FreakyFashion_HostAddress}}/api/Categories/2
Accept: application/json

### Get Category By Slug
GET {{FreakyFashion_HostAddress}}/api/Categories/slug=t-shirts
Accept: application/json

### Create Category
POST {{FreakyFashion_HostAddress}}/api/Categories/
Accept: application/json
Content-type: application/json
{
  "name": "Hats",
  "image": "/images/hats.jpg"
}

### Create Category without body
POST {{FreakyFashion_HostAddress}}/api/Categories/
Accept: application/json
Content-type: application/json
{

}

### Delete Category
DELETE {{FreakyFashion_HostAddress}}/api/Categories/8
Accept: application/json