@FreakyFashion_HostAddress = https://freakyfashion-webapp.azurewebsites.net/

### Get all products
GET {{FreakyFashion_HostAddress}}/api/Products/
Accept: application/json

### Get product by Id
GET {{FreakyFashion_HostAddress}}/api/Products/4
Accept: application/json

### Get product by slug
GET {{FreakyFashion_HostAddress}}/api/Products/slug=yellow-cap
Accept: application/json

### Create a new product
POST {{FreakyFashion_HostAddress}}/api/Products/
Accept: application/json
Content-Type: application/json
{
    "name": "Gray Hoodie",
    "Description": "A warm gray hoodie",
    "Price": 199,
    "Image": "/images/gray-hoodie.png",
    "CategoryId": 5
}

### Create without body
POST {{FreakyFashion_HostAddress}}/api/Products/
Accept: application/json
Content-Type: application/json
{

}

### Delete product
DELETE {{FreakyFashion_HostAddress}}/api/Products/6
Accept: application/json

### -------------------------------------------------------------
### Get All Categories
GET {{FreakyFashion_HostAddress}}/api/Categories/
Accept: application/json

### Get Category By Id
GET {{FreakyFashion_HostAddress}}/api/Categories/2
Accept: application/json

### Get Category By Slug
GET {{FreakyFashion_HostAddress}}/api/Categories/slug=t-shirts
Accept: application/json

### Create Category
POST {{FreakyFashion_HostAddress}}/api/Categories/
Accept: application/json
Content-type: application/json
{
  "name": "Hoodies",
  "image": "/images/hoodies.jpg"
}

### Create Category without body
POST {{FreakyFashion_HostAddress}}/api/Categories/
Accept: application/json
Content-type: application/json
{

}

### Delete Category
DELETE {{FreakyFashion_HostAddress}}/api/Categories/8
Accept: application/json